<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "exposition_qnvt"
 *
 * Auto generated by Extension Builder 2018-07-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'exposition qnvt',
    'description' => 'Projet exposition',
    'category' => 'plugin',
    'author' => 'Thomas COURTOT, Valentin GRAGLIA, Nicolas DECRUCQ, Quentin BERGMAN',
    'author_email' => 'thomas.courtot@etu.u-bordeaux.fr, valentin.graglia@etu.u-bordeaux.fr, nicolas.decrucq@etu.u-bordeaux.fr, quentin.bergman@etu.u-bordeaux.fr',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
